#! some variables need to be configurable externally
#! we can specify them in a separate file or a separate
#! YAML document node

#@ load("@ytt:data", "data")
#@ def caContainers(input, value, networkSpec):
#@   env = [{ "name": "FABRIC_CA_HOME", "value": "/etc/hyperledger/fabric-ca-server"}]
#@   env.append({"name": "FABRIC_CA_SERVER_CA_NAME", "value": "{}".format(input)})
#@   env.append({"name": "FABRIC_CA_SERVER_CA_KEYFILE", "value": "/etc/hyperledger/fabric/artifacts/ca/ca_private.key"})
#@   env.append({"name": "FABRIC_CA_SERVER_CA_CERTFILE", "value": "/etc/hyperledger/fabric/artifacts/ca/ca-cert.pem"})
#@   env.append({"name": "FABRIC_CA_SERVER_TLS_ENABLED", "value": "{}".format(networkSpec.tls) })
#@   env.append({"name": "FABRIC_CA_SERVER_TLS_KEYFILE", "value": "/etc/hyperledger/fabric/artifacts/tlsca/tlsca_private.key"})
#@   env.append({"name": "FABRIC_CA_SERVER_TLS_CERTFILE", "value": "/etc/hyperledger/fabric/artifacts/tlsca/tlsca-cert.pem"})
#@   resources = {"limits":{"cpu": "0.2", "memory": "0.5Gi"}, "requests":{"cpu":"0.2", "memory":"0.5Gi"}}
#@   volumeMounts = [{"mountPath": "/etc/hyperledger/fabric/certparser", "name": "certsparser"}]
#@   volumeMounts.append({"mountPath": "/etc/hyperledger/fabric/secret", "name": "mspsecret"})
#@   output = [{"name": input,"image": "hyperledger/fabric-ca", "imagePullPolicy": "Always", "env": env, "resources": resources,"volumeMounts":volumeMounts, "command":["/bin/bash"], "args":["-c","cd /etc/hyperledger/fabric/ && cp certparser/certs-parser.sh . && chmod +x ./certs-parser.sh && ./certs-parser.sh {}.json && fabric-ca-server start -b admin:adminpw -d" .format(input) ]}]
#@   return output
#@ end


#@ def peerContainers(input, value, networkSpec, mspId):
#@   env = [{ "name": "CORE_VM_ENDPOINT", "value": "unix:///var/run/docker.sock"}]
#@   env.append({"name": "CORE_PEER_GOSSIP_USELEADERELECTION", "value": "True"})
#@   env.append({"name": "CORE_PEER_GOSSIP_ORGLEADER", "value": "false"})
#@   env.append({"name": "CORE_PEER_LISTENADDRESS", "value": "0.0.0.0:7051"})
#@   env.append({"name": "CORE_PEER_CHAINCODELISTENADDRESS", "value": "0.0.0.0:7052"})
#@   env.append({"name": "CORE_PEER_TLS_ENABLED", "value": "{}".format(networkSpec.tls) })
#@   env.append({"name": "FABRIC_LOGGING_SPEC", "value": networkSpec.peer_fabric_logging_spec })
#@   env.append({"name": "CORE_PEER_TLS_CERT_FILE", "value": "/etc/hyperledger/fabric/artifacts/tls/server.crt"})
#@   env.append({"name": "CORE_PEER_TLS_KEY_FILE", "value": "/etc/hyperledger/fabric/artifacts/tls/server.key"})
#@   env.append({"name": "CORE_PEER_TLS_ROOTCERT_FILE", "value": "/etc/hyperledger/fabric/artifacts/msp/tlscacerts/tlsca-cert.pem"})
#@   env.append({"name": "CORE_PEER_ID", "value": "{}".format(input)})
#@   env.append({"name": "CORE_PEER_GOSSIP_EXTERNALENDPOINT", "value": "{}:7051".format(input)})
#@   env.append({"name": "CORE_PEER_ADDRESS", "value": "{}:7051".format(input)})
#@   env.append({"name": "CORE_PEER_CHAINCODEADDRESS", "value": "{}:7052".format(input)})
#@   env.append({"name": "CORE_PEER_LOCALMSPID", "value": "{}".format(mspId)})
#@   env.append({"name": "CORE_PEER_MSPCONFIGPATH", "value": "/etc/hyperledger/fabric/artifacts/msp"})

#@   volumeMounts = [{"mountPath": "/etc/hyperledger/fabric/certparser", "name": "certsparser"}]
#@   volumeMounts.append({"mountPath": "/etc/hyperledger/fabric/secret", "name": "mspsecret"})
#@   resources = {"limits":{"cpu": "1", "memory": "1Gi"}, "requests":{"cpu":"1", "memory":"1Gi"}}

#@   if networkSpec.db_type == "couchdb":
#@     env.append({"name": "CORE_LEDGER_STATE_STATEDATABASE", "value": "CouchDB"})
#@     env.append({"name": "CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS", "value": "localhost:5984"})
#@     container = {"name":"couchdb-{}".format(input), "image": "hyperledger/fabric-couchdb", "imagePullPolicy": "Always", "securityContext":{"privileged":True}, "resources":{"limits":{"cpu": "0.1","memory": "1Gi"},"requests":{"cpu": "0.1","memory": "1Gi"} }}
#@     output = [{"name": input,"image": "hyperledger/fabric-peer", "imagePullPolicy": "Always", "securityContext" : { "privileged": True }, "env": env, "volumeMounts":volumeMounts, "command": ["/bin/bash"], "args":["-c","cd /etc/hyperledger/fabric/ && cp certparser/certs-parser.sh . && chmod +x ./certs-parser.sh && ./certs-parser.sh {}.json && peer node start" .format(input) ], "resources": resources}, container]
#@   else:
#@      output = [{"name": input,"image": "hyperledger/fabric-peer", "imagePullPolicy": "Always", "securityContext" : { "privileged": True }, "env": env, "volumeMounts":volumeMounts, "command": ["/bin/bash"], "args":["-c","cd /etc/hyperledger/fabric/ && cp certparser/certs-parser.sh . && chmod +x ./certs-parser.sh && ./certs-parser.sh {}.json && peer node start" .format(input) ], "resources": resources}]
#@   end
#@   return output
#@ end


#@ def ordererContainers(input, value, networkSpec, mspId):
#@   env = [{ "name": "ORDERER_GENERAL_LISTENADDRESS", "value": "0.0.0.0"}]
#@   env.append({"name": "ORDERER_GENERAL_GENESISMETHOD", "value": "file"})
#@   env.append({"name": "FABRIC_LOGGING_SPEC", "value": networkSpec.orderer_fabric_logging_spec})
#@   env.append({"name": "ORDERER_GENERAL_TLS_ENABLED", "value": "{}".format(networkSpec.tls)})
#@   env.append({"name": "ORDERER_GENERAL_GENESISFILE", "value": "/etc/hyperledger/fabric/genesisblock/genesis.block"})
#@   env.append({"name": "ORDERER_GENERAL_LOCALMSPID", "value": mspId })
#@   env.append({"name": "ORDERER_GENERAL_LOCALMSPDIR", "value": "/etc/hyperledger/fabric/artifacts/msp"})
#@   env.append({"name": "ORDERER_GENERAL_TLS_SERVERHOSTOVERRIDE", "value": input})
#@   env.append({"name": "ORDERER_GENERAL_TLS_PRIVATEKEY", "value": "/etc/hyperledger/fabric/artifacts/tls/server.key"})
#@   env.append({"name": "ORDERER_GENERAL_TLS_CERTIFICATE", "value": "/etc/hyperledger/fabric/artifacts/tls/server.crt"})
#@   env.append({"name": "ORDERER_GENERAL_TLS_ROOTCAS", "value": "[/etc/hyperledger/fabric/artifacts/msp/tlscacerts/tlsca-cert.pem]"})
#@   env.append({"name": "ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY", "value": "/etc/hyperledger/fabric/artifacts/tls/server.key"})
#@   env.append({"name": "ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE", "value": "/etc/hyperledger/fabric/artifacts/tls/server.crt"})

#@   volumeMounts = [{"mountPath": "/etc/hyperledger/fabric/certparser", "name": "certsparser"}]
#@   volumeMounts.append({"mountPath": "/etc/hyperledger/fabric/secret", "name": "mspsecret"})
#@   volumeMounts.append({"mountPath": "/etc/hyperledger/fabric/genesisblock", "name": "genesisblock"})
#@   resources = {"limits":{"cpu": "1", "memory": "1Gi"}, "requests":{"cpu":"1", "memory":"1Gi"}}
#@   output = [{"name": input,"image": "hyperledger/fabric-orderer", "imagePullPolicy": "Always",  "env": env, "resources": resources,"volumeMounts": volumeMounts,"command":["/bin/bash"], "args":["-c","cd /etc/hyperledger/fabric/ && cp certparser/certs-parser.sh . && chmod +x ./certs-parser.sh && ./certs-parser.sh {}.json && orderer" .format(input) ] }]
#@   return output
#@ end

#@ def spec(input,orgName, value, networkSpec, mspId):
#@   type = {}
#@   specData = {}
#@   if input.startswith("ca"):
#@     type = "ca"
#@     specData = {"volumes":[{"name":"certsparser","configMap":{"name":"certsparser"}},{"name":"mspsecret","secret":{"secretName":"{}".format(input)}}],
#@             "affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"weight":1,"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"type","operator": "In","values":["{}".format(value)]}]},"topologyKey":"kubernetes.io/hostname"}}]}},
#@              "containers": caContainers(input, orgName, networkSpec)}
#@   elif input.startswith("orderer"):
#@     type = "orderer"
#@     specData = {"volumes":[{"name":"certsparser","configMap":{"name":"certsparser"}},{"name":"mspsecret","secret":{"secretName":"{}".format(input)}},{"name":"genesisblock","secret":{"secretName":"genesisblock"}}],
#@             "affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"weight":1,"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"type","operator": "In","values":["{}".format(value)]}]},"topologyKey":"kubernetes.io/hostname"}}]}},
#@              "containers": ordererContainers(input, orgName, networkSpec, mspId)}
#@   else:
#@     type = "peer"
#@     specData = {"volumes":[{"name":"certsparser","configMap":{"name":"certsparser"}},{"name":"mspsecret","secret":{"secretName":"{}".format(input)}}],
#@             "affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"weight":1,"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"type","operator": "In","values":["{}".format(value)]}]},"topologyKey":"kubernetes.io/hostname"}}]}},
#@              "containers": peerContainers(input, orgName, networkSpec, mspId)}
#@   end
#@   selector = {"matchLabels":{"k8s-app": input,"type": type}}
#@   metadata = {"labels":{"k8s-app": input,"type":type}}
#@   template = {"metadata":metadata,"spec":specData}
#@   output = {"selector":selector, "serviceName": input, "replicas": 1, "template": template}
#@   return output
#@ end

#@ for i in range(0,len(data.values.peer_organizations)):
#@ organization = data.values.peer_organizations[i]
#@ for j in range(0, organization.num_ca):
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: #@ "ca{}-{}".format(j, organization.name)
spec: #@ spec("ca{}-{}".format(j, organization.name),organization.name,"peer", data.values, organization.msp_id)
#@ end
#@ for j in range(0, organization.num_peers):
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: #@ "peer{}-{}".format(j, organization.name)
spec: #@ spec("peer{}-{}".format(j, organization.name),organization.name,"peer", data.values, organization.msp_id)
#@ end
#@ end

#@ for i in range(0,len(data.values.orderer_organizations)):
#@ organization = data.values.orderer_organizations[i]
#@ for j in range(0, organization.num_ca):
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: #@ "ca{}-{}".format(j, organization.name)
spec: #@ spec("ca{}-{}".format(j, organization.name),organization.name,"orderer", data.values, organization.msp_id)
#@ end
#@ for j in range(0, organization.num_orderers):
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: #@ "orderer{}-{}".format(j, organization.name)
spec: #@ spec("orderer{}-{}".format(j, organization.name),organization.name,"orderer", data.values, organization.msp_id)
#@ end
#@ end