---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: ca-org
  name: ca-org
spec:
  selector:
    k8s-app: ca-org
  ports:
    - name: port1
      port: 7054
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: peer-org
  name: peer-org
spec:
  selector:
    k8s-app: peer-org
  ports:
  - name: port1
    port: 7051
  - name: port2
    port: 7052
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: orderer-ordererorg
  name: orderer-ordererorg
spec:
  selector:
    k8s-app: orderer-ordererorg
  ports:
    - name: port1
      port: 7050