# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
    behave:

services:
    ca.example.com:
        extends:
            file: docker-compose-base.yml
            service: ca
        container_name: ca.example.com
        environment:
            - FABRIC_CA_SERVER_CA_NAME=ca.example.com
              #- BOOTSTRAP_USER_PASS=example.com-admin:example.com-adminpw
            - BOOTSTRAP_USER_PASS=admin:adminpw
            - FABRIC_CA_SERVER_CSR_CN=ca.example.com
            - FABRIC_CA_SERVER_CSR_HOSTS=ca.example.com
            - FABRIC_CA_SERVER_CA_CERTFILE=/var/hyperledger/fabric-ca-server-config/ca.example.com-cert.pem
        command: /bin/bash -c 'fabric-ca-server start -b $${BOOTSTRAP_USER_PASS} -d'
        volumes:
            - ../configs/${CORE_PEER_NETWORKID}/ordererOrganizations/example.com/ca:/var/hyperledger/fabric-ca-server-config
            - ../configs/${CORE_PEER_NETWORKID}/example.com:/var/hyperledger/fabric-ca-server
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}

    ca.org1.example.com:
        extends:
            file: docker-compose-base.yml
            service: ca
        container_name: ca.org1.example.com
        environment:
            - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
            - FABRIC_CA_SERVER_CA_CERTFILE=/var/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
            - FABRIC_CA_SERVER_TLS_CERTFILE=/var/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=${FABRIC_CA_SERVER_ORG1_TLS_KEYFILE}
            - FABRIC_CA_SERVER_CA_KEYFILE=${FABRIC_CA_SERVER_ORG1_CA_KEYFILE}
              #- BOOTSTRAP_USER_PASS=org1.example.com-admin:org1.example.com-adminpw
            - BOOTSTRAP_USER_PASS=admin:adminpw
            - FABRIC_CA_SERVER_CSR_CN=ca.org1.example.com
            - FABRIC_CA_SERVER_CSR_HOSTS=ca.org1.example.com
        ports:
            - "8054:7054"
        command: /bin/bash -c 'fabric-ca-server start -b $${BOOTSTRAP_USER_PASS} -d'
        volumes:
            - ../configs/${CORE_PEER_NETWORKID}/org1.example.com:/var/hyperledger/fabric-ca-server
            - ../configs/${CORE_PEER_NETWORKID}/peerOrganizations/org1.example.com/ca:/var/hyperledger/fabric-ca-server-config
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}

    ca.org2.example.com:
        extends:
            file: docker-compose-base.yml
            service: ca
        container_name: ca.org2.example.com
        environment:
            - FABRIC_CA_SERVER_CA_NAME=ca.org2.example.com
            - FABRIC_CA_SERVER_TLS_CERTFILE=/var/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
            - FABRIC_CA_SERVER_CA_CERTFILE=/var/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=${FABRIC_CA_SERVER_ORG2_TLS_KEYFILE}
            - FABRIC_CA_SERVER_CA_KEYFILE=${FABRIC_CA_SERVER_ORG2_CA_KEYFILE}
              #- BOOTSTRAP_USER_PASS=org2.example.com-admin:org2.example.com-adminpw
            - BOOTSTRAP_USER_PASS=admin:adminpw
            - FABRIC_CA_SERVER_CSR_CN=ca.org2.example.com
            - FABRIC_CA_SERVER_CSR_HOSTS=ca.org2.example.com
        command: /bin/bash -c 'fabric-ca-server start -b $${BOOTSTRAP_USER_PASS} -d'
        volumes:
            - ../configs/${CORE_PEER_NETWORKID}/org2.example.com:/var/hyperledger/fabric-ca-server
            - ../configs/${CORE_PEER_NETWORKID}/peerOrganizations/org2.example.com/ca:/var/hyperledger/fabric-ca-server-config
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}

#    ca.example.com:
#        extends:
#            file: docker-compose-base.yml
#            service: ca
#        container_name: ca.example.com
#        environment:
#            - FABRIC_CA_SERVER_CA_NAME=ca.example.com
#            #- FABRIC_CA_SERVER_TLS_CERTFILE=/var/hyperledger/fabric-ca-server-config/ca.example.com-cert.pem
#            #- FABRIC_CA_SERVER_CA_CERTFILE=/var/hyperledger/fabric-ca-server-config/ca.example.com-cert.pem
#            #- FABRIC_CA_SERVER_TLS_KEYFILE=${FABRIC_CA_SERVER_ORG0_TLS_KEYFILE}
#            #- FABRIC_CA_SERVER_CA_KEYFILE=${FABRIC_CA_SERVER_ORG0_CA_KEYFILE}
#            - BOOTSTRAP_USER_PASS=example.com-admin:example.com-adminpw
#            - FABRIC_CA_SERVER_CSR_CN=ca.example.com
#            - FABRIC_CA_SERVER_CSR_HOSTS=ca.example.com
#        command: /bin/bash -c 'fabric-ca-server start -b $${BOOTSTRAP_USER_PASS} -d'
#        networks:
#          behave:
#             aliases:
#               - ${CORE_PEER_NETWORKID}
#
#    ca.org1.example.com:
#        image: hyperledger/fabric-ca
#        container_name: ca.org1.example.com
#        environment:
#            - FABRIC_CA_HOME=/var/hyperledger/fabric-ca-server
#            - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
#            - FABRIC_CA_SERVER_TLS_ENABLED=${FABRIC_CA_SERVER_TLS_ENABLED}
#            - FABRIC_CA_SERVER_TLS_CERTFILE=/var/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
#            - FABRIC_CA_SERVER_CA_CERTFILE=/var/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
#            - FABRIC_CA_SERVER_TLS_KEYFILE=${FABRIC_CA_SERVER_ORG1_TLS_KEYFILE}
#            - FABRIC_CA_SERVER_CA_KEYFILE=${FABRIC_CA_SERVER_ORG1_CA_KEYFILE}
#            - FABRIC_CA_SERVER_DEBUG=true
#            - BOOTSTRAP_USER_PASS=org1.example.com-admin:org1.example.com-adminpw
#            - FABRIC_CA_SERVER_CSR_CN=ca.org1.example.com
#            - FABRIC_CA_SERVER_CSR_HOSTS=ca.org1.example.com
#        ports:
#            - "8054:7054"
#        command: /bin/bash -c 'fabric-ca-server start -b $${BOOTSTRAP_USER_PASS} -d'
#        volumes:
#            - ../configs/${CORE_PEER_NETWORKID}/org1.example.com:/var/hyperledger/fabric-ca-server
#            - ../configs/${CORE_PEER_NETWORKID}:/var/hyperledger/fabric-ca-server-config
#        networks:
#          behave:
#             aliases:
#               - ${CORE_PEER_NETWORKID}

    orderer0.example.com:
        image: hyperledger/fabric-ca-orderer
        environment:
            - FABRIC_CA_CLIENT_HOME=/var/hyperledger/orderer
            - ENROLLMENT_URL=https://orderer0:orderer0pw@ca.example.com:7054
            - CA_ADMIN_ENROLLMENT_URL=https://example.com-admin:example.com-adminpw@ca.example.com:7054
            - ADMIN_USER=admin-orderer0
            - ADMIN_PASS=admin-orderer0pw
            - BOOTSTRAP_USER=orderer0
            - BOOTSTRAP_PASS=orderer0pw
            - BOOTSTRAP_USER_PASS=orderer0:orderer0pw
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/configs/ca.example.com-cert.pem]
            - FABRIC_CA_CLIENT_TLS_CERTFILES=/var/hyperledger/configs/ca.example.com-cert.pem
            - ORG_ADMIN_CERT=/var/hyperledger/configs/example.com/users/Admin/msp/cacerts/ca-example-com-7054.pem
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/msp/keystore/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/msp/signcerts/cert.pem
        command: /bin/bash -c 'sleep 5; /var/hyperledger/scripts/orderer.sh'
        volumes:
            - ../configs:/var/hyperledger/scripts
            - ../configs/${CORE_PEER_NETWORKID}/example.com/orderer0.example.com:/var/hyperledger/orderer
            - ../configs/${CORE_PEER_NETWORKID}/example.com/orderer0.example.com/msp:/var/hyperledger/msp
            - ../configs/${CORE_PEER_NETWORKID}/example.com/orderer0.example.com/tls:/var/hyperledger/tls
        depends_on:
            - ca.example.com
            - ca.org1.example.com
            - ca.org2.example.com


    orderer1.example.com:
        image: hyperledger/fabric-ca-orderer
        environment:
            - FABRIC_CA_CLIENT_HOME=/var/hyperledger/orderer
            - ORDERER_HOME=/var/hyperledger/orderer
            - ENROLLMENT_URL=https://orderer1:orderer1pw@ca.example.com:7054
            - CA_ADMIN_ENROLLMENT_URL=https://example.com-admin:example.com-adminpw@ca.example.com:7054
            - ADMIN_USER=admin-orderer1
            - ADMIN_PASS=admin-orderer1pw
            - BOOTSTRAP_USER=orderer1
            - BOOTSTRAP_PASS=orderer1pw
            - BOOTSTRAP_USER_PASS=orderer1:orderer1pw
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/configs/ca.example.com-cert.pem]
            - FABRIC_CA_CLIENT_TLS_CERTFILES=/var/hyperledger/configs/ca.example.com-cert.pem
            - ORG_ADMIN_CERT=/var/hyperledger/configs/example.com/users/Admin/msp/cacerts/ca-example-com-7054.pem
        command: /bin/bash -c 'sleep 5; /var/hyperledger/scripts/orderer.sh'
        #command: /bin/bash -c 'sleep 10; fabric-ca-client enroll -d --enrollment.profile tls -u $${ENROLLMENT_URL} -M /var/hyperledger/tls --csr.hosts $${ORDERER_HOST}; mv /var/hyperledger/tls/server.crt /var/hyperledger/tls/signcerts/.; mv /var/hyperledger/tls/server.key /var/hyperledger/tls/keystore/.; fabric-ca-client enroll -d -u $${ENROLLMENT_URL} -M $${ORDERER_GENERAL_LOCALMSPDIR}; orderer'
        volumes:
            - ../configs/${CORE_PEER_NETWORKID}:/var/hyperledger/configs
            - ../configs/${CORE_PEER_NETWORKID}/example.com/orderer1.example.com:/var/hyperledger/orderer
            - ../configs/${CORE_PEER_NETWORKID}/example.com/orderer1.example.com/msp:/var/hyperledger/msp
            - ../configs/${CORE_PEER_NETWORKID}/example.com/orderer1.example.com/tls:/var/hyperledger/tls
        depends_on:
            - ca.example.com
            - ca.org1.example.com
            - ca.org2.example.com

    orderer2.example.com:
        image: hyperledger/fabric-ca-orderer
        environment:
            - ENROLLMENT_URL=https://orderer2:orderer2pw@ca.example.com:7054
            - BOOTSTRAP_USER_PASS=orderer2:orderer2pw
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/configs/ca.example.com-cert.pem]
        command: /bin/bash -c 'sleep 5; fabric-ca-client enroll -d --enrollment.profile tls -u $${ENROLLMENT_URL} -M /var/hyperledger/tls --csr.hosts $${ORDERER_HOST}; fabric-ca-client enroll -d -u $${ENROLLMENT_URL} -M $${ORDERER_GENERAL_LOCALMSPDIR}; orderer'
        volumes:
            - ../configs/${CORE_PEER_NETWORKID}:/var/hyperledger/configs
            - ../configs/${CORE_PEER_NETWORKID}/example.com/orderer2.example.com:/var/hyperledger/orderer
            - ../configs/${CORE_PEER_NETWORKID}/example.com/orderer2.example.com/msp:/var/hyperledger/msp
            - ../configs/${CORE_PEER_NETWORKID}/example.com/orderer2.example.com/tls:/var/hyperledger/tls
        depends_on:
            - ca.example.com
            - ca.org1.example.com
            - ca.org2.example.com


    peer0.org1.example.com:
        image: hyperledger/fabric-ca-peer
        environment:
            - FABRIC_CA_CLIENT_HOME=/var/hyperledger/peer
            - ENROLLMENT_URL=https://peer0org1:peer0org1pw@ca.org1:7054
            - CA_ADMIN_ENROLLMENT_URL=https://org1.example.com-admin:org1.example.com-adminpw@ca.org1.example.com:7054
            - ORG=org1
            - BOOTSTRAP_USER_PASS=peer0org1:peer0org1pw
            - BOOTSTRAP_USER=peer0org1
            - BOOTSTRAP_PASS=peer0org1pw
            - ADMIN_USER=admin-peer0org1
            - ADMIN_PASS=admin-peer0org1pw
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/configs/ca.org1.example.com-cert.pem
            #- CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
            - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/msp/signcerts/cert.pem
            #- CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
            - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/msp/keystore/server.key
            - FABRIC_CA_CLIENT_TLS_CERTFILES=/var/hyperledger/configs/ca.org1.example.com-cert.pem
        #command: peer node start
        #command: /bin/bash -c 'sleep 5; fabric-ca-client enroll -d --enrollment.profile tls -u $${ENROLLMENT_URL} -M /var/hyperledger/tls --csr.hosts $${CORE_PEER_ID}; fabric-ca-client enroll -d -u $${ENROLLMENT_URL} -M $${CORE_PEER_MSPCONFIGPATH} --enrollment.profile tls --id.name $${BOOTSTRAP_USER} --id.secret $${BOOTSTRAP_PASS} --id.affiliation org1.example.com; peer node start'
        command: /bin/bash -c 'sleep 5; /var/hyperledger/scripts/peer.sh'
        volumes:
            - ../configs:/var/hyperledger/scripts
            - ../configs/${CORE_PEER_NETWORKID}:/var/hyperledger/configs
            - ../configs/${CORE_PEER_NETWORKID}/org1.example.com/peer0.org1.example.com:/var/hyperledger/peer
            - ../configs/${CORE_PEER_NETWORKID}/org1.example.com/peer0.org1.example.com/msp:/var/hyperledger/msp
            - ../configs/${CORE_PEER_NETWORKID}/org1.example.com/peer0.org1.example.com/tls:/var/hyperledger/tls
        depends_on:
            - orderer0.example.com
            - orderer1.example.com
            - orderer2.example.com

    peer1.org1.example.com:
        image: hyperledger/fabric-ca-peer
        environment:
            #- ENROLLMENT_URL=https://peer1org1:peer1org1pw@ca.org1.example.com:7054
            - ENROLLMENT_URL=https://org1.example.com-admin:org1.example.com-adminpw@ca.org1.example.com:7054
            - BOOTSTRAP_USER_PASS=peer1org1:peer1org1pw
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/configs/ca.org1.example.com-cert.pem
            - FABRIC_CA_CLIENT_TLS_CERTFILES=/var/hyperledger/configs/ca.org1.example.com-cert.pem
        command: /bin/bash -c 'sleep 10; fabric-ca-client enroll -d --enrollment.profile tls -u $${ENROLLMENT_URL} -M /var/hyperledger/tls --csr.hosts $${CORE_PEER_ID}; fabric-ca-client enroll -d -u $${ENROLLMENT_URL} -M $${CORE_PEER_MSPCONFIGPATH}; peer node start'
        volumes:
            - ../configs/${CORE_PEER_NETWORKID}:/var/hyperledger/configs
        depends_on:
            - orderer0.example.com
            - peer0.org1.example.com

    peer0.org2.example.com:
        image: hyperledger/fabric-ca-peer
        environment:
            - ENROLLMENT_URL=https://peer0org2:peer0org2pw@ca.org2.example.com:7054
            - CA_ADMIN_ENROLLMENT_URL=https://org2.example.com-admin:org2.example.com-adminpw@ca.org2.example.com:7054
            - ORG=org2
            - BOOTSTRAP_USER_PASS=peer0org2:peer0org2pw
            - BOOTSTRAP_USER=peer0org2
            - BOOTSTRAP_PASS=peer0org2pw
            - ADMIN_USER=admin-peer0org2
            - ADMIN_PASS=admin-peer0org2pw
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/configs/ca.org2.example.com-cert.pem
            - FABRIC_CA_CLIENT_TLS_CERTFILES=/var/hyperledger/configs/ca.org2.example.com-cert.pem
        command: /bin/bash -c 'sleep 10; fabric-ca-client enroll -d --enrollment.profile tls -u $${ENROLLMENT_URL} -M /var/hyperledger/tls --csr.hosts $${CORE_PEER_ID}; fabric-ca-client enroll -d -u $${ENROLLMENT_URL} -M $${CORE_PEER_MSPCONFIGPATH}; peer node start'
        volumes:
            - ../configs/${CORE_PEER_NETWORKID}:/var/hyperledger/configs
        depends_on:
            - orderer0.example.com
            - orderer1.example.com
            - orderer2.example.com

    peer1.org2.example.com:
        image: hyperledger/fabric-ca-peer
        environment:
            #- ENROLLMENT_URL=https://peer1org2:peer1org2pw@ca.org2.example.com:7054
            - ENROLLMENT_URL=https://org2.example.com-admin:org2.example.com-adminpw@ca.org2.example.com:7054
            - BOOTSTRAP_USER_PASS=peer1org2:peer1org2pw
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/configs/ca.org2.example.com-cert.pem
            - FABRIC_CA_CLIENT_TLS_CERTFILES=/var/hyperledger/configs/ca.org2.example.com-cert.pem
        command: /bin/bash -c 'sleep 10; fabric-ca-client enroll -d --enrollment.profile tls -u $${ENROLLMENT_URL} -M /var/hyperledger/tls --csr.hosts $${CORE_PEER_ID}; fabric-ca-client enroll -d -u $${ENROLLMENT_URL} -M $${CORE_PEER_MSPCONFIGPATH}; peer node start'
        volumes:
            - ../configs/${CORE_PEER_NETWORKID}:/var/hyperledger/configs
        depends_on:
            - orderer0.example.com
            - peer0.org2.example.com
