# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
---
# PTE service credential file
version: 1.0
test-network:
  gopath: GOPATH
  orderer:
    orderer0:
      mspid: OrdererOrg
      adminPath: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/msp
      url: grpcs://localhost:5005
      server-hostname: orderer0.example.com
      tls_cacerts: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
    orderer1:
      mspid: OrdererOrg
      adminPath: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/msp
      url: grpcs://localhost:5006
      server-hostname: orderer1.example.com
      tls_cacerts: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
    orderer2:
      mspid: OrdererOrg
      adminPath: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/msp
      url: grpcs://localhost:5007
      server-hostname: orderer2.example.com
      tls_cacerts: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
# org3
  org3:
    name: PeerOrg3
    mspid: PeerOrg3
    adminPath: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org3.example.com/users/Admin@org3.example.com/msp
    ordererID: orderer1
    ca:
      url: https://localhost:7056
      name: ca2
    username: admin
    secret: adminpw
    # org3 peer1
    peer1:
      requests: grpcs://localhost:7065
      server-hostname: peer0.org3.example.com
      tls_cacerts: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org3.example.com/tlsca/tlsca.org3.example.com-cert.pem
    # org3 peer2
    peer2:
      requests: grpcs://localhost:7066
      server-hostname: peer1.org3.example.com
      tls_cacerts: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org3.example.com/tlsca/tlsca.org3.example.com-cert.pem
   #  org4
  org4:
    name: PeerOrg4
    mspid: PeerOrg4
    adminPath: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org4.example.com/users/Admin@org4.example.com/msp
    ordererID: orderer1
    ca:
      url: https://localhost:7057
      name: ca3
    username: admin
    secret: adminpw
    # org4 peer1
    peer1:
      requests: grpcs://localhost:7067
      server-hostname: peer0.org4.example.com
      tls_cacerts: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org4.example.com/tlsca/tlsca.org4.example.com-cert.pem
    # org4 peer2
    peer2:
      requests: grpcs://localhost:7068
      server-hostname: peer1.org4.example.com
      tls_cacerts: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org4.example.com/tlsca/tlsca.org4.example.com-cert.pem
