# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
---
# PTE service credential file
version: 1.0
test-network:
  gopath: GOPATH
  orderer:
    orderer0:
      mspid: OrdererOrg
      adminPath: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/msp
      url: grpcs://localhost:5005
      server-hostname: orderer0.example.com
      tls_cacerts: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
    orderer1:
      mspid: OrdererOrg
      adminPath: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/msp
      url: grpcs://localhost:5006
      server-hostname: orderer1.example.com
      tls_cacerts: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
    orderer2:
      mspid: OrdererOrg
      adminPath: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/msp
      url: grpcs://localhost:5007
      server-hostname: orderer2.example.com
      tls_cacerts: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
  org1:
    name: PeerOrg1
    mspid: PeerOrg1
    adminPath: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    ordererID: orderer0
    ca:
      url: https://localhost:7054
      name: ca0
    username: admin
    secret: adminpw
    peer1:
      requests: grpcs://localhost:7061
      server-hostname: peer0.org1.example.com
      tls_cacerts: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem
    peer2:
      requests: grpcs://localhost:7062
      server-hostname: peer1.org1.example.com
      tls_cacerts: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem
  org2:
    name: PeerOrg2
    mspid: PeerOrg2
    adminPath: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp
    ordererID: orderer0
    ca:
      url: https://localhost:7055
      name: ca1
    username: admin
    secret: adminpw
    peer1:
      requests: grpcs://localhost:7063
      server-hostname: peer0.org2.example.com
      tls_cacerts: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem
    peer2:
      requests: grpcs://localhost:7064
      server-hostname: peer1.org2.example.com
      tls_cacerts: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem
