# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
---
# PTE service credential file
version: 1.0
test-network:
  gopath: GOPATH
  orderer:
    orderer0:
      mspid: OrdererOrg
      adminPath: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/msp
      url: grpcs://localhost:5005
      server-hostname: orderer0.example.com
      tls_cacerts: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
    orderer1:
      mspid: OrdererOrg
      adminPath: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/msp
      url: grpcs://localhost:5006
      server-hostname: orderer1.example.com
      tls_cacerts: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
    orderer2:
      mspid: OrdererOrg
      adminPath: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/msp
      url: grpcs://localhost:5007
      server-hostname: orderer2.example.com
      tls_cacerts: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
# org5
  org5:
    name: PeerOrg5
    mspid: PeerOrg5
    adminPath: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org5.example.com/users/Admin@org5.example.com/msp
    ordererID: orderer2
    ca:
      url: https://localhost:7058
      name: ca4
    username: admin
    secret: adminpw
    # org5 peer1
    peer1:
      requests: grpcs://localhost:7069
      server-hostname: peer0.org5.example.com
      tls_cacerts: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org5.example.com/tlsca/tlsca.org5.example.com-cert.pem
    # org5 peer2
    peer2:
      requests: grpcs://localhost:7070
      server-hostname: peer1.org5.example.com
      tls_cacerts: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org5.example.com/tlsca/tlsca.org5.example.com-cert.pem
   #  org6
  org6:
    name: PeerOrg6
    mspid: PeerOrg6
    adminPath: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org6.example.com/users/Admin@org6.example.com/msp
    ordererID: orderer2
    ca:
      url: https://localhost:7059
      name: ca5
    username: admin
    secret: adminpw
    # org6 peer1
    peer1:
      requests: grpcs://localhost:7071
      server-hostname: peer0.org6.example.com
      tls_cacerts: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org6.example.com/tlsca/tlsca.org6.example.com-cert.pem
    # org6 peer2
    peer2:
      requests: grpcs://localhost:7072
      server-hostname: peer1.org6.example.com
      tls_cacerts: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org6.example.com/tlsca/tlsca.org6.example.com-cert.pem
